name: Docker Image CI

on:
  push:
    branches: [ "main", "khalid_docker_test" ]
  pull_request:
    branches: [ "main", "khalid_docker_test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t libassfuzz .

    - name: Run Docker container
      run: docker run -d --name libassfuzzcontainer libassfuzz

    - name: Check if Docker container is running
      run: docker ps | grep libassfuzzcontainer

    - name: Get Docker container logs
      run: docker logs libassfuzzcontainer