name: 'Fuzzing action'

on:
  push:
    branches: [ main, khalid_docker_test, setareh ]
  pull_request:
    branches: [ main, khalid_docker_test, setareh ]

runs:
  using: 'docker'
  image: 'Dockerfile'
